server:
  port: 9003

spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label  # ??? ???? ??? ??? ?? ??
    stream: # ?? ??? ??? ?? ??
      bindings:
        packlabel-in-0: # ?? ???
          destination: order-accepted # ???? ??? ??? ??? ???? ?? ??(??MQ? ?????)
          group: ${spring.application.name} # ??? ??? ?? ??? ??(?????? ??? ??) => ?? ???? ??? ??
        packlabel-out-0:  # ?? ???
          destination: order-dispatched # ???? ??? ??? ??? ???? ?? ??(??MQ? ?????)

  # ??MQ
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-time: 5s
